# Generated by Django 5.1.5 on 2025-07-25 22:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NuraDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('activation_code', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(default='disconnected', max_length=20)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nura_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
